--
-- PostgreSQL database dump
--

\restrict NefTx2TAyNvMxhQKUofj8fdsry8MlhkI7gcleVUAb3D2dp11MHftYJgLYGU1T0B

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: auth_project_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO auth_project_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_profile; Type: TABLE; Schema: public; Owner: auth_project_user
--

CREATE TABLE public.accounts_profile (
    id bigint NOT NULL,
    age integer,
    user_id bigint NOT NULL,
    CONSTRAINT accounts_profile_age_check CHECK ((age >= 0))
);


ALTER TABLE public.accounts_profile OWNER TO auth_project_user;

--
-- Name: accounts_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: auth_project_user
--

ALTER TABLE public.accounts_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: auth_project_user
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    access_duration interval NOT NULL,
    created_at timestamp with time zone NOT NULL,
    is_valid boolean NOT NULL
);


ALTER TABLE public.accounts_user OWNER TO auth_project_user;

--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: auth_project_user
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO auth_project_user;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: auth_project_user
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: auth_project_user
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: auth_project_user
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO auth_project_user;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: auth_project_user
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: auth_project_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO auth_project_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: auth_project_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: auth_project_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO auth_project_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: auth_project_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: auth_project_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO auth_project_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: auth_project_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: auth_project_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO auth_project_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: auth_project_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: auth_project_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO auth_project_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: auth_project_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: auth_project_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO auth_project_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: auth_project_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: auth_project_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO auth_project_user;

--
-- Data for Name: accounts_profile; Type: TABLE DATA; Schema: public; Owner: auth_project_user
--

COPY public.accounts_profile (id, age, user_id) FROM stdin;
\.


--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: auth_project_user
--

COPY public.accounts_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, access_duration, created_at, is_valid) FROM stdin;
6	pbkdf2_sha256$1200000$Pp66HLheqJoySyi7RBk7qE$KGDzK5ihmwloHgtTzkGoK27HknFFXeYqoP3fCwDBDiQ=	\N	f	testuser				f	t	2026-02-05 11:46:24.583433+00	00:02:00	2026-02-05 11:46:25.635141+00	t
7	pbkdf2_sha256$1200000$wna4HBxaLsVg7f5ihykIFo$nyp6xri12X2rvZKF8kCSfHXEPWINOK6lXLtslZNfhRo=	\N	f	testuser1				f	t	2026-02-05 11:50:38.487652+00	00:02:00	2026-02-05 11:50:39.546739+00	t
8	pbkdf2_sha256$1200000$mhTCtQSWAdPtmeRQNurH8R$6Z5NzKF+t9lB8jlKbui4tKUc2+16t9uOk1fPIvz7OyE=	\N	f	testuser4				f	t	2026-02-05 11:53:20.572421+00	00:02:00	2026-02-05 11:53:21.695579+00	t
9	pbkdf2_sha256$1200000$aGtMTwDPwHmkqHI9EgGTyG$ljvO9hu0B+NSt/Pn+vHT1yoXQzcn7n4r8iO10Cb8t9M=	\N	f	testuser3				f	t	2026-02-05 11:57:16.210863+00	00:02:00	2026-02-05 11:57:17.326716+00	t
12	pbkdf2_sha256$1200000$cCADSPuA6Wu3KLIyvpjiRH$ZL8Lr95VMg6xIQPOI4ppNfJv6Q/UFNwgNCnp0b7OUrw=	\N	f	testuser9				f	t	2026-02-05 12:09:22.257284+00	00:05:00	2026-02-05 12:09:23.37536+00	t
13	pbkdf2_sha256$1200000$9kseN72LxaMIgj7Nao5WNW$5oNywg6KLHsatXx7I0+VphyDjMH7+kaSKeXyb6/VE20=	\N	f	testuser10				f	t	2026-02-05 12:51:20.616252+00	00:02:00	2026-02-05 12:51:23.635631+00	t
14	pbkdf2_sha256$1200000$AQn1X7yZ5oKMfFZ4dffHZG$E2X/FVwYDcVJFnbGLWFYA6aMBUYPHg9N225l38ae1RU=	\N	f	testuser11				f	t	2026-02-05 13:49:54.781131+00	00:01:00	2026-02-05 13:49:56.091754+00	t
15	pbkdf2_sha256$1200000$qE7Dhz1Nx693rd7cA5Leyg$Caasc2qJNu2ezuNZSS1HcUKTRCCO8cw5qm7iq1alWpY=	\N	f	testuser12				f	t	2026-02-05 13:51:29.21586+00	00:01:00	2026-02-05 13:51:30.550026+00	t
16	pbkdf2_sha256$1200000$RM9Ye1Bwb07ec3ruPb9lXO$Y6esgvLN9GVyZODc24X5wriHFI+wOQu3ZSzXjo7zgPA=	\N	f	testuser2				f	t	2026-02-13 06:07:27.769583+00	00:02:00	2026-02-13 06:07:28.814188+00	t
17	pbkdf2_sha256$1200000$32hJQV4G8fX89gXPMsEdjS$q4ofaps51x7QFyl8ngmn4n8f099wshm+f4FacyzOzCg=	\N	f	testuser22				f	t	2026-02-13 06:14:25.472176+00	00:02:00	2026-02-13 06:14:27.482894+00	t
18	pbkdf2_sha256$1200000$FQHXdIg0q8T7JBIimHhQJW$r7PFkI6GZ9jPckMbCRThWZNWFMdaus94ES5iBNeccIg=	\N	f	testuser23				f	t	2026-02-13 13:36:29.95731+00	00:02:00	2026-02-13 13:36:31.00265+00	t
19	pbkdf2_sha256$1200000$NcIFPwEMpeCK9L2vDCvlrP$GWCHgJASbLfYhDGvU8a7ulgKbhQp9GnZwugt5l3IojQ=	\N	f	testuser25				f	t	2026-02-13 14:47:15.360291+00	00:02:00	2026-02-13 14:47:17.377107+00	t
20	pbkdf2_sha256$1200000$dGr9pT9R1LFTYF6VeOgFqX$j8/6lIicHCE68lq3D593WOa7uQnmNokzBBOUUFPeQGc=	\N	f	testuser28				f	t	2026-02-13 14:48:41.880559+00	00:02:00	2026-02-13 14:48:43.308169+00	t
21	pbkdf2_sha256$1200000$UmE8w5GhZAZ6Wjkila2Avy$ocaxjhR7/x8MdMlpRWAOFYpKDn/OsOPE02FI/xInZpw=	\N	f	testuser29				f	t	2026-02-13 15:07:17.30995+00	00:01:00	2026-02-13 15:07:18.367977+00	t
22	pbkdf2_sha256$1200000$Dxixx3iXjWgeVXEdXc3Stx$kc5RZkQ0cZJotbhD+sPQuAsF8Z4zuMTuOLuM8R4Uvuw=	\N	f	testuser30				f	t	2026-02-13 15:12:34.335251+00	00:01:00	2026-02-13 15:12:35.453174+00	t
23	pbkdf2_sha256$1200000$UTc9qMfO95x4SmoXjKUNuO$1qJKM08yiPcONlYwg24riEfSdnMRos2AkYHRTWW76Yc=	\N	f	maimoona				f	t	2026-02-13 17:48:20.16501+00	00:01:00	2026-02-13 17:48:21.224657+00	t
24	pbkdf2_sha256$1200000$4wJ3X6eUuZJ9WTzY5bJG9z$622LAZiIDxcGwFwP9obsm9oF52ml6ANP5RG4iKy9OKs=	\N	f	maim				f	t	2026-02-14 03:05:48.717179+00	00:01:00	2026-02-14 03:05:49.764046+00	t
25	pbkdf2_sha256$1200000$xNE8C0CeK9urMbWBkiCRci$HZnL61TeUhgrpEJFwRKaSknyG3hFnJzOGWQPg7Oeldw=	\N	f	m				f	t	2026-02-14 04:37:29.084269+00	00:01:00	2026-02-14 04:37:30.184782+00	t
26	pbkdf2_sha256$1200000$wOFcQzNpSNNxsM4YzdHEFX$fJmCae6ip0680AnqBebTh92tDIm6RKXIcGlqdIFrkj8=	\N	f	n				f	t	2026-02-14 04:45:21.658909+00	00:01:00	2026-02-14 04:45:22.70383+00	t
27	pbkdf2_sha256$1200000$xCWP1YPqcZXfCOce6EPBct$Uv6064eYVwOlbrTgmZpUlILrHWue4Kl7DwXTNcRcaGg=	\N	f	o				f	t	2026-02-14 04:48:06.192789+00	00:01:00	2026-02-14 04:48:07.298687+00	t
28	pbkdf2_sha256$1200000$VnFrgZNvyyYdG202Qyx8QS$VF9FZG2bDhM6Pjeb4DjtFNv39sJD8+dn9J0GVxEtseY=	\N	f	p				f	t	2026-02-14 04:55:43.72727+00	00:01:00	2026-02-14 04:55:44.811452+00	t
29	pbkdf2_sha256$1200000$20yagmCSqlF3CrRoqV1exQ$Q0vENIaYTilND5ULgYyOpsQ8RA9oZQXy3T5b0BgAbz0=	\N	f	q				f	t	2026-02-14 05:06:29.751005+00	00:01:00	2026-02-14 05:06:30.900015+00	t
30	pbkdf2_sha256$1200000$l1bz04LZ3fq2KTl41SnJu7$8IjWPsGysnEB5qk5S0ixJggdIFe9eYaVOXi8AAuWiFg=	\N	f	user1				f	t	2026-03-01 14:19:32.903679+00	00:05:00	2026-03-01 14:19:34.619786+00	t
31	pbkdf2_sha256$1200000$Gl6uBIJyeTDOvtDdi7KAxk$4l5YCP2vPxNSkyIkKm8Of70tn3y8rmJuqoAj3DHzAkc=	\N	f	user2				f	t	2026-03-01 14:19:59.674976+00	00:10:00	2026-03-01 14:20:01.506598+00	t
32	pbkdf2_sha256$1200000$k6YLxulFCFNIuqZWFJxQng$cEltkSpqnMYkPR6GiOKAnRyjnoEfgP+YjQty3U5i0sg=	\N	f	newuser				f	t	2026-03-01 14:25:47.548148+00	00:10:00	2026-03-01 14:25:48.722248+00	t
33	pbkdf2_sha256$1200000$Q9GkLB3tL5yhmnhOSxjlmK$rj9xNk3lW0AlpipZB0dVXYWLsGQhZExSHEgOpZ7zxEE=	\N	f	newuser1				f	t	2026-03-01 14:58:46.06287+00	00:01:00	2026-03-01 14:58:47.13185+00	t
34	pbkdf2_sha256$1200000$HUPcZpQLXvbJfWqgKLmPER$aUNgfZmdjvUOV5B+ec46Tqw1Y0Exym0a2M1uJjM48No=	\N	f	newuser2				f	t	2026-03-01 14:59:32.366517+00	00:01:00	2026-03-01 14:59:33.420552+00	t
35	pbkdf2_sha256$1200000$nba1291MVMS39LbGh1eQEi$Lan0eEcrgN3bkgHrEogmOUo9YqOCzCdic3wVCmmsREg=	\N	f	newuser3				f	t	2026-03-01 15:01:08.20893+00	00:03:00	2026-03-01 15:01:09.366593+00	t
36	pbkdf2_sha256$1200000$q1cjZhrbKcVAAi9GvlID0E$cql79xdvWU2CBhxYwbGLbjAitOQBGgTaZI0DDcl/LjA=	\N	f	newuser4				f	t	2026-03-01 15:05:35.768137+00	00:01:00	2026-03-01 15:05:36.807011+00	t
37	pbkdf2_sha256$1200000$Mie4TPX2iyCyWzhW8J0sUr$5yyOE8G9egwFQXusXTAKmDveZPhWZ9rOSMczqk4uktA=	\N	f	taufiq				f	t	2026-03-01 15:17:29.279127+00	00:10:00	2026-03-01 15:17:30.893331+00	t
38	pbkdf2_sha256$1200000$uXeZRFxcdt7rnflJQYVLwM$fbbk90gwOaHmpLtNT4hKBxanisRfTwDhns/nUHarGJM=	\N	f	taufiq1				f	t	2026-03-01 15:28:00.083507+00	00:10:00	2026-03-01 15:28:01.80408+00	t
39	pbkdf2_sha256$1200000$WYivX2nq8l5gJHfIWHrMvU$kTbfTk4wtO9VZwiAzJ933/u63MUQpBN3kWUZsChIUJE=	\N	f	taufiq2				f	t	2026-03-01 15:30:56.194611+00	00:01:00	2026-03-01 15:30:58.566635+00	t
40	pbkdf2_sha256$1200000$igHioJvFxfyasScoa9QS2X$8F5492KtX3KUshHsSRhyN6R5olAdKP1xi1KIEmEbP00=	\N	f	taufiq3				f	t	2026-03-01 15:33:59.355868+00	00:02:00	2026-03-01 15:34:02.385354+00	t
41	pbkdf2_sha256$1200000$N8Y5R97jHjSIoH78BQToM0$jsNHX3N0Vsgu099nESdu1kPiyHsfLx15Ee78U1dLNNQ=	\N	f	taufiq4				f	t	2026-03-01 16:25:07.121958+00	00:02:00	2026-03-01 16:25:08.521158+00	t
42	pbkdf2_sha256$1200000$Lfy0Rh7LvmAMgrisj4J8gp$WQnKBeKBOF4XnBnh3YyMlGms3RsKyEuu9UnO2CcC6GM=	\N	f	taufiq5				f	t	2026-03-01 16:28:15.629817+00	00:01:00	2026-03-01 16:28:17.889791+00	t
\.


--
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: auth_project_user
--

COPY public.accounts_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: auth_project_user
--

COPY public.accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: auth_project_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: auth_project_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: auth_project_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	7	add_user
22	Can change user	7	change_user
23	Can delete user	7	delete_user
24	Can view user	7	view_user
25	Can add profile	6	add_profile
26	Can change profile	6	change_profile
27	Can delete profile	6	delete_profile
28	Can view profile	6	view_profile
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: auth_project_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: auth_project_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	accounts	profile
7	accounts	user
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: auth_project_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-02-05 07:28:12.2603+00
2	contenttypes	0002_remove_content_type_name	2026-02-05 07:28:12.276043+00
3	auth	0001_initial	2026-02-05 07:28:12.333286+00
4	auth	0002_alter_permission_name_max_length	2026-02-05 07:28:12.349305+00
5	auth	0003_alter_user_email_max_length	2026-02-05 07:28:12.353655+00
6	auth	0004_alter_user_username_opts	2026-02-05 07:28:12.360121+00
7	auth	0005_alter_user_last_login_null	2026-02-05 07:28:12.364645+00
8	auth	0006_require_contenttypes_0002	2026-02-05 07:28:12.366255+00
9	auth	0007_alter_validators_add_error_messages	2026-02-05 07:28:12.370674+00
10	auth	0008_alter_user_username_max_length	2026-02-05 07:28:12.376028+00
11	auth	0009_alter_user_last_name_max_length	2026-02-05 07:28:12.385054+00
12	auth	0010_alter_group_name_max_length	2026-02-05 07:28:12.391525+00
13	auth	0011_update_proxy_permissions	2026-02-05 07:28:12.397888+00
14	auth	0012_alter_user_first_name_max_length	2026-02-05 07:28:12.402869+00
15	accounts	0001_initial	2026-02-05 07:28:12.455019+00
16	accounts	0002_profile	2026-02-05 07:28:12.470069+00
17	admin	0001_initial	2026-02-05 07:28:12.488808+00
18	admin	0002_logentry_remove_auto_add	2026-02-05 07:28:12.500806+00
19	admin	0003_logentry_add_action_flag_choices	2026-02-05 07:28:12.508444+00
20	sessions	0001_initial	2026-02-05 07:28:12.519772+00
21	accounts	0003_remove_profile_address_remove_profile_dob_and_more	2026-02-05 10:37:50.537075+00
22	accounts	0004_alter_user_created_at	2026-02-05 11:09:33.130129+00
23	accounts	0005_user_is_valid	2026-02-05 11:37:19.233752+00
24	accounts	0006_alter_user_created_at	2026-02-05 11:46:14.183225+00
25	accounts	0007_alter_user_access_duration	2026-02-05 11:58:21.431635+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: auth_project_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Name: accounts_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: auth_project_user
--

SELECT pg_catalog.setval('public.accounts_profile_id_seq', 1, false);


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: auth_project_user
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: auth_project_user
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 42, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: auth_project_user
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: auth_project_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: auth_project_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: auth_project_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 28, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: auth_project_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: auth_project_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 7, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: auth_project_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 25, true);


--
-- Name: accounts_profile accounts_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_pkey PRIMARY KEY (id);


--
-- Name: accounts_profile accounts_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_user_id_key UNIQUE (user_id);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: auth_project_user
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: auth_project_user
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: auth_project_user
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: auth_project_user
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: auth_project_user
--

CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: auth_project_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: auth_project_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: auth_project_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: auth_project_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: auth_project_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: auth_project_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: auth_project_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: auth_project_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: accounts_profile accounts_profile_user_id_49a85d32_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_user_id_49a85d32_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: auth_project_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict NefTx2TAyNvMxhQKUofj8fdsry8MlhkI7gcleVUAb3D2dp11MHftYJgLYGU1T0B

