# Generated by Django 6.0.1 on 2026-02-02 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_access_duration_user_created_at_user_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=24)),
        ),
    ]
