# Generated by Django 6.0.1 on 2026-02-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_duration',
            field=models.DurationField(),
        ),
    ]
